### ISSUE TITLE
Python API - RX timeouts when radio is idle for a little while

### ISSUE THREAD

**Issue by Djgreene730** [EttusResearch/uhd#418]
## Issue Description ##
I'm using the Python API of UHD to control an N210 in Jupyter. I create a radio object, rx and tx streamers, and I periodically run a `stream_mode.num_done` thread to collect samples. Trouble is, if I don't call the receive streamer frequently enough (i.e. more than a minute) I get a timeout error and need to recreate the whole radio object to get things moving again.
```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-7-4c10c9cac967>", line 265, in receive_samples
    assert(False), f"{rx_metadata.strerror()}"
AssertionError: ERROR_CODE_TIMEOUT
```
The transmit streamer always seems fine. I've checked that I'm collecting all the samples I ask for.

## Setup Details ##
Ubuntu 18.04
Python 3.6
GNU C++ version 7.5.0
Boost_106501
UHD_4.0.0.0-46-g57ca4235
USRP N210 R4

## Expected Behavior ##
I expect to be able to call the receive thread, which runs a `num_done` call, collect the number of specified samples, and then leave it alone for a while until I ask for more.

## Actual Behaviour ##
Calls to the receive streamer timeout after about a minute of no use.

## Steps to reproduce the problem ##
I'll resubmit a code example later.

## Additional Information ##
What's the recommended way to recover from an RX Timeout, besides recreating the entire radio object and streamers? I need to do this to get things running again.

**Comment by jrocnuck** [comment]
This may not fix your problem, but it may help others who land here looking at your issue.

I have seen similar problems with UHD 4 and an X300 radio on Fedora 33 Linux.
The scenario is to run a receiver for about 150 seconds with any sample rate / freq / gain (and also with mtu 8000 or 1742).  Then stop the receiver for about 150 seconds and attempt to restart it (all in the same running process).  Instantly I get an async message followed by the timeout / overflow issue.    The radio basically will never clear its state in the firmware from this point forward no matter what stream command is issued.

I have partially figured out what happens.  In my case, I have the standard firewalld (with default rules/settings) running and once I issue the restart of the radio (after the long wait), I get a burst of data packets and then I see my host barking ICMP DESTINATION UNREACHABLE packets back to the x300, however those are blocked by the firewall, resulting in a repeatable NON-RECOVERABLE state.

When I disable the firewall, I do not see these ICMP DESTINATION unreachable messages going from the host to the x300.

I have dug fairly deep in all the diagnostic logs, etc. on the host and cannot see any cases where UDP packet errors/drops occur.  I haven't enabled extensive logging in the firewall yet to see if it's causing the issues of the destination UDP port/address being unreachable.  At this point, if I had to guess, the firewall is causing enough of a delay to cause the overflow situation.  The bad news is this means if a process ever overflowed long enough, the radio would become unrecoverable.

I am still shocked that this problem of NON-RECOVERY has not been fixed in the drivers after all this time.  I've seen messages in forums dating back to 2017/2018 with this state in the drivers.
The bottom line when a stop stream command is issued, this driver needs to clear any bad state in the control processing period and start fresh.  But from what I can tell, a stop command does not clear previous run inconsistent state.

From a reliability standpoint, that's a show stopper (basically unacceptable) for deployments running in real time where an entire radio (multiple channels) will require reset of all channels to recover one.
