### ISSUE TITLE
Hang in usrp device creation

### ISSUE THREAD

**Issue by SimplicityGuy** [EttusResearch/uhd#74]
We have an Ettus USRP N200 that we're using for testing on a Debian Jessie machine. It's directly connected to the machine over Ethernet (so there's no switch involved). What we encounter is that over long test runs, we will eventually see a hang coming from `uhd_usrp_make`.

When the hang is encountered, we've captured a stack trace:

```
#0  0x00007efca0ffcddb in __libc_recv (fd=1029, buf=0x688d000, n=1472, flags=-1) at ../sysdeps/unix/sysv/linux/x86_64/recv.c:33
#1  0x00007efc761519fb in udp_zero_copy_asio_impl::get_recv_buff(double) () from /usr/lib/x86_64-linux-gnu/libuhd.so.003
#2  0x00007efc75f7bcf9 in usrp2_fifo_ctrl::make(boost::shared_ptr<uhd::transport::zero_copy_if>) () from /usr/lib/x86_64-linux-gnu/libuhd.so.003
#3  0x00007efc75f640f4 in usrp2_impl::usrp2_impl(uhd::device_addr_t const&) () from /usr/lib/x86_64-linux-gnu/libuhd.so.003
#4  0x00007efc75f72076 in usrp2_make(uhd::device_addr_t const&) () from /usr/lib/x86_64-linux-gnu/libuhd.so.003
#5  0x00007efc75f1e9fc in boost::detail::function::function_invoker1<boost::shared_ptr<uhd::device> (*)(uhd::device_addr_t const&), boost::shared_ptr<uhd::device>, uhd::device_addr_t const&>::invoke(boost::detail::function::function_buffer&, uhd::device_addr_t const&) () from /usr/lib/x86_64-linux-gnu/libuhd.so.003
#6  0x00007efc761a5120 in uhd::device::make(uhd::device_addr_t const&, uhd::device::device_filter_t, unsigned long) () from /usr/lib/x86_64-linux-gnu/libuhd.so.003
#7  0x00007efc75caba0d in uhd::usrp::multi_usrp::make(uhd::device_addr_t const&) () from /usr/lib/x86_64-linux-gnu/libuhd.so.003
#8  0x00007efc75ce0e6d in uhd_usrp_make () from /usr/lib/x86_64-linux-gnu/libuhd.so.003
#9  0x00007efc765fb426 in usrp_get_samples (dev_args=<optimized out>, fc=<optimized out>, fs=10000000, ugain=0, num_samps=3000000, use_agc=<optimized out>, use_gpsdo=false, output_buffer=0x97f6fc0)
    at usrp_ctypes.c:168
<snip... bunch of Python call stack info since we're using this from Python...>
```

Frame 9 is our code that provides an interface to our tests.

While it take a bit of time to reproduce the problem, we can reproduce consistently after about 40 minutes of run time. Our tests are designed to init the device, capture some data, clean up the device, and repeat under different test conditions.

From `uhd_config_info`:

```
linux; GNU C++ version 4.9.2; Boost_105500; UHD_003.011.000.git-95-g811444b1
```

From `uname -a`:

```
Linux test-machine 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
```

From `uhd_usrp_probe`:

```
linux; GNU C++ version 4.9.2; Boost_105500; UHD_003.011.000.git-95-g811444b1

-- Opening a USRP2/N-Series device...
-- Current recv frame size: 1472 bytes
-- Current send frame size: 1472 bytes
  _____________________________________________________
 /
|       Device: USRP2 / N-Series Device
|     _____________________________________________________
|    /
|   |       Mboard: N200r4
|   |   hardware: 2576
|   |   mac-addr: ff:ff:ff:ff:ff:ff
|   |   ip-addr: 192.168.0.2
|   |   subnet: 255.255.255.255
|   |   gateway: 255.255.255.255
|   |   gpsdo: none
|   |   serial: 4095
|   |   FW Version: 12.4
|   |   FPGA Version: 11.1
|   |   
|   |   Time sources:  none, external, _external_, mimo
|   |   Clock sources: internal, external, mimo
|   |   Sensors: mimo_locked, ref_locked
|   |     _____________________________________________________
|   |    /
|   |   |       RX DSP: 0
|   |   |   
|   |   |   Freq range: -50.000 to 50.000 MHz
|   |     _____________________________________________________
|   |    /
|   |   |       RX DSP: 1
|   |   |   
|   |   |   Freq range: -50.000 to 50.000 MHz
|   |     _____________________________________________________
|   |    /
|   |   |       RX Dboard: A
|   |   |   ID: SBX (0x0054)
|   |   |   Serial: 30ACD99
|   |   |     _____________________________________________________
|   |   |    /
|   |   |   |       RX Frontend: 0
|   |   |   |   Name: SBXv3 RX
|   |   |   |   Antennas: TX/RX, RX2, CAL
|   |   |   |   Sensors: lo_locked
|   |   |   |   Freq range: 400.000 to 4400.000 MHz
|   |   |   |   Gain range PGA0: 0.0 to 31.5 step 0.5 dB
|   |   |   |   Bandwidth range: 40000000.0 to 40000000.0 step 0.0 Hz
|   |   |   |   Connection Type: IQ
|   |   |   |   Uses LO offset: No
|   |   |     _____________________________________________________
|   |   |    /
|   |   |   |       RX Codec: A
|   |   |   |   Name: ads62p44
|   |   |   |   Gain range digital: 0.0 to 6.0 step 0.5 dB
|   |   |   |   Gain range fine: 0.0 to 0.5 step 0.1 dB
|   |     _____________________________________________________
|   |    /
|   |   |       TX DSP: 0
|   |   |   
|   |   |   Freq range: -50.000 to 50.000 MHz
|   |     _____________________________________________________
|   |    /
|   |   |       TX Dboard: A
|   |   |   ID: SBX (0x0055)
|   |   |   Serial: 30ACD99
|   |   |     _____________________________________________________
|   |   |    /
|   |   |   |       TX Frontend: 0
|   |   |   |   Name: SBXv3 TX
|   |   |   |   Antennas: TX/RX, CAL
|   |   |   |   Sensors: lo_locked
|   |   |   |   Freq range: 400.000 to 4400.000 MHz
|   |   |   |   Gain range PGA0: 0.0 to 31.5 step 0.5 dB
|   |   |   |   Bandwidth range: 40000000.0 to 40000000.0 step 0.0 Hz
|   |   |   |   Connection Type: QI
|   |   |   |   Uses LO offset: No
|   |   |     _____________________________________________________
|   |   |    /
|   |   |   |       TX Codec: A
|   |   |   |   Name: ad9777
|   |   |   |   Gain Elements: None
```

**Comment by mbr0wn** [comment]
So, basically, this is what you're doing:
- Run a receive test that spawns and destroys a USRP session
- Repeat

...and that's all it takes to reproduce this?

**Comment by SimplicityGuy** [comment]
Yes. I can share the "capture" code with you.

**Comment by SimplicityGuy** [comment]
Digging into this a bit further shows that we're typically creating and freeing the device about 170 times before we see the issue. It's fairly consistent, sometimes it's 165 times, sometimes it's around 175 times.

We also power cycle the USRP N200 after each 50 or so measurements. This is a mere precaution since we've seen issues that over a long period of time of being turned on we no longer can communicate with it (this is not unique to this USRP N200; we've seen this on multiple units).

**Comment by mbr0wn** [comment]
Looks like @michael-west helped track this down to an issue in the app. Please correct if that's not the case.
