### ISSUE TITLE
USRP X300 error: Dirty: RxStreamer#1[INPUT_EDGE:0 atomic_item_size]

### ISSUE THREAD

**Issue by NIDHIPANDA** [EttusResearch/uhd#797]
Hello,

I am having USRP X300 device with following tool versions:

Vivado 2021.1 - AR76780n,
GNU radio version - v3.11.0.0git-820-g2adbd4ea
UHD version - UHD_4.7.0.0-84-gbdada1ed

I have added FFT and Spliter RFNoC blocks in my bit file. The "uhd_usrp_probe" command shows correct connection in the blocks. 

|   |       RFNoC blocks on this device:
|   |   
|   |   * 0/DDC#0
|   |   * 0/FFT#0
|   |   * 0/Radio#0
|   |   * 0/Replay#0
|   |   * 0/SplitStream#0
|     _____________________________________________________
|    /
|   |       Static connections on this device:

|   |   * 0/Radio#0:0==>0/DDC#0:0
|   |   * 0/Radio#0:1==>0/DDC#0:1
|   |   * 0/DDC#0:1==>0/SEP#0:0
|   |   * 0/DDC#0:0==>0/SplitStream#0:0
|   |   * 0/SplitStream#0:1==>0/FFT#0:0
|   |   * 0/SplitStream#0:0==>0/SEP#2:0
|   |   * 0/FFT#0:0==>0/SEP#1:0
|   |   * 0/SEP#3:0==>0/Replay#0:0
|   |   * 0/Replay#0:0==>0/SEP#3:0
|   |   * 0/SEP#4:0==>0/Replay#0:1
|   |   * 0/Replay#0:1==>0/SEP#4:0

However, on running example code available on GNU RADIO **"rfnoc_split_stream.grc"**. I get following error:
_Please run: sudo sysctl -w net.core.wmem_max=2453333
[WARNING] [0/Radio#0] Attempting to set tick rate to 0. Skipping.
[ERROR] [RFNOC::GRAPH::DETAIL] The following properties could not be resolved:
[ERROR] [RFNOC::GRAPH::DETAIL] Dirty: RxStreamer#1[INPUT_EDGE:0 atomic_item_size]
Traceback (most recent call last):
  File "/home/quasar/gnuradio/gr-uhd/examples/grc/rfnoc_split_stream.py", line 357, in <module>
    main()
  File "/home/quasar/gnuradio/gr-uhd/examples/grc/rfnoc_split_stream.py", line 336, in main
    tb.start()
  File "/usr/local/lib/python3.8/dist-packages/gnuradio/gr/top_block.py", line 116, in start
    top_block_start_unlocked(self._impl, max_noutput_items)
RuntimeError: RfnocError: ResolveError: Could not resolve properties.

I tried by changing FFT size to 256 and also SPP same for all blocks. but I get same error. Please help me to resolve this issue.

Regards
Nidhi

**Comment by mbr0wn** [comment]
@NIDHIPANDA can you try again with the most recent UHD? We did a bunch of updates to the FFT block.
